image: docker:latest

variables:
 DOCKER_DRIVER: overlay

services:
- docker:dind
- kaiwinter/docker-java8-maven

before_script:
- docker info
- apk add --no-cache py-pip
- pip install docker-compose

build:
 stage: build
 script:
 - docker-compose up -d
test:
 stage: test
 script: 
 - "mvn clean test"

after_script:
 - docker info
