image: lmear/fred:v2

services:
  - selenium/hub
  
services:
  - selenium/node-chrome

variables:
  links:
    - selenium/hub

before_script:
  - . /xvfb.sh
  
stages:
  - test
  - coverage
  
test:
  script: "mvn clean test"
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
    - virtuoso-test-results/*.json
    expire_in: 1 week
    
coverage:
  script: "mvn jacoco:report"
