image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
 - docker:dind

before_script:
 - docker info

build:
  stage: build
  script:
  - docker build -t my-docker-image
  - docker run my-docker-imasge script/to/run/tests


image: kaiwinter/docker-java8-maven

stages:
  - test
  - coverage
test:
 script: "mvn clean test"
coverage:
 script: "mvn jacoco:report"