
version: '2'

# @author: ABDUL SAIF
# @date  : 14/11/2016-15/11/2016

# This YAML file Executes Docker and boots up the following:
# Sonarqube, Jenkins, Selenium Hub, Jira, Confluence, Firefox and Chrome.

# Use run command in terminal: docker-compose up -d
# Check hosts: sudo nano /etc/hosts
# Show hidden files: defaults write com.apple.finder AppleShowAllFiles YES,
# Refresh Finder: killall finder

#                        Local Disk    :   Virtual Disk
# Change volumes: /Users/XXXX/XXXX/XXXX:/var/jenkins_home
# Where XXXX is insert your jenkins source folder.

iimage: kaiwinter/docker-java8-maven

stages:
  - test
  - coverage

test:
  stage: test
  script: "mvn clean test"

coverage:
  stage: coverage
  script: "mvn jacoco:report"

  #Run Selenium Hub
  Saifhub:
    hostname: selenium_hub
    container_name: SaifHub
    image: selenium/hub
    ports:
      - 4444:4444
