image: pworrall/milkchocolate

before_script: 
  - . /xvfb.sh
 stages:
  -test
 test:
 script: "mvn clean test"
 artifacts:
     name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
     paths:
     -target/site/jacoco/*.html
     expire_in: 1 week