image: kaiwinter/docker-java8-maven
job1:
 script:
 - "mvn install -B"
 - "cat target/site/jacoco/index.html"

  Saifhub:
    hostname: selenium_hub
    container_name: SaifHub
    image: selenium/hub
    ports:
      - 4444:4444
