image: lmear/fred

variables:
 DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info
- Xvfb :99 -screen 5 1024x768x8 &
#- apk add --no-cache py-pip
#- pip install docker-compose

build:
 stage: build
 script:

# - docker-compose up -d
# - docker build -t automation-test docker/
# - docker run --privileged automation-test

#test:
# stage: test
# script: 
# - "mvn clean test"

after_script:
 - docker info
