# @author: ABDUL SAIF
# @date  : 25/11/2016-15/11/2016

image: adrianchan/maven-xvfb

before_script:
  - service xvfb start

stages:
  - test

test:
  script:
    - mvn clean test
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
    - virtuoso-test-results/*.json
    expire_in: 1 week
