image: lmear/fred:v2

before_script:
  - . /xvfb.sh
  - . /selenium.sh
  
stages:
  - test
  - coverage
  
test:
  script: "mvn clean test"
coverage:
  script: "mvn jacoco:report"

test:
  
  script:
    
  - mvn clean test
  artifacts:

  name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    
  paths:
    
  - virtuoso-test-results/*.json
    
  expire_in: 1 week