# @author: ABDUL SAIF
# @date  : 14/11/2016-15/11/2016

image: lmear/fred:v2

before_script:
  - . /xvfb.sh

stages:
  - test
  - coverage

test:
  script: "mvn clean test"
coverage:
  script: "mvn jacoco:report"
