<<<<<<< HEAD
# @author: ABDUL SAIF
# @date  : 29/11/2016

image: saifabs/chocolate

before_script:
  - . /xvfb.sh

stages:
  - test

test:
  script:
    - mvn clean verify
    - ls -lrt

  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
    - target/site/jacoco/*
    - target/site/serenity/*
    expire_in: 1 week
=======
image: kaiwinter/docker-java8-maven
stages:
  - test
  - coverage
test:
 script: "mvn clean test"
coverage:
 script: "mvn jacoco:report"
>>>>>>> 2beba4862217ff97589258f5f649ad7eee1d6cdf
