image: lmear/fred:v2

services:
  - selenium/hub
  

before_script:
  - . /xvfb.sh
  
stages:
  - test
    
test:
  script: "mvn clean test jacoco:report"
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
    - virtuoso-test-results/*.json
    expire_in: 1 week