image: kaiwinter/docker-java8-maven
image: selenium/hub
image: selenium/node-chrome
image: selenium/node-firefox
stages:
  - test
  - coverage
test:
 script: "mvn clean test"
coverage:
 script: "mvn jacoco:report"