# @author: ABDUL SAIF
# @date  : 29/11/2016

image: saifabs/chocolate

before_script:
  - . /xvfb.sh

  cache:
  untracked: true
  paths:
  - binaries/

stages:
  - test
  - cache

test:
  script:
    - mvn clean verify -q
    - ls -lrt

  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
    - target/site/jacoco/*
    - target/site/serenity/*
    expire_in: 1 week
