version: '2'

services:

  jenkins:
    image: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - C:\Users\Les\Documents\Kitematic\jenkins\var\jenkins_home:/var/jenkins_home

  selenium_hub:
    hostname: selenium_hub
    image: selenium/hub
    ports:
      - 4444:4444

  firefox:
    image: selenium/node-firefox
    links:
      - selenium_hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444/tcp

  chrome:
    image: selenium/node-chrome
    links:
      - selenium_hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444/tcp

  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    volumes:
      - C:\Users\Les\Documents\Kitematic\sonarqube\opt\sonarqube:/opt/sonarqube/data
      - C:\Users\Les\Documents\Kitematic\sonarqube\opt\sonarqube:/opt/sonarqube/extensions