version: '2'

services:

  selenium_hub:
    hostname: selenium_hub
    image: selenium/hub
    ports:
      - 4444:4444

  firefox:
    image: selenium/node-firefox
    links:
      - selenium_hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444/tcp

  chrome:
    image: selenium/node-chrome
    links:
      - selenium_hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444/tcp
